# Generated by Django 4.2.3 on 2023-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
            ],
        ),
    ]
